{% set name = "sigtools" %}
{% set version = "4.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sigtools-{{ version }}.tar.gz
  sha256: 7cc84a0ba56e34b7f15e433744268f10e0c4a76d6bfece89cecc1a1ca91138b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - six

test:
  imports:
    - sigtools
    - sigtools.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://sigtools.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Utilities for working with inspect.Signature objects.
  dev_url: https://github.com/epsy/sigtools

extra:
  recipe-maintainers:
    - proinsias
